[tool.black]
line-length = 100

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]  # Allow long lines for better readability in AI projects

[tool.ruff.format]
quote-style = "double"
indent-style = "space" 